### ISSUE TITLE
Google Drive links are not publicly accessible

### ISSUE THREAD

**Issue by styler00dollar** [yingchen001/BAT-Fill#1]
The pretrained models can only be downloaded with e-mail authorization. Please make the links public. Thanks.
![unknown](https://user-images.githubusercontent.com/51405565/137619789-ec4d4a5c-9518-41e0-bc9c-e310a871179b.png)

**Comment by yingchen001** [comment]
Hi styler00dollar, 

I've made them public, please try again, thank you.

**Comment by styler00dollar** [comment]
Works, thanks.
