### ISSUE TITLE
Discriminator weights

### ISSUE THREAD

**Issue by samuro95** [yingchen001/BAT-Fill#2]
Hi,
Thank you for your work,
I would be interested in your pretrained discriminator weights, could you provide them ? 
Thanks a lot,

**Comment by yingchen001** [comment]
Hi,

Here are the discriminator weights, hope they will help. Thank you.

- [PSV](https://drive.google.com/file/d/1tgMrqNLnAu-GvYLj4cCaEynCTOq5F3MT/view?usp=sharing)
- [CelebaHQ](https://drive.google.com/file/d/1CXW6vowVQHYW5VBSGSk8ku_dljqet5Zj/view?usp=sharing)
- [Places](https://drive.google.com/file/d/1FPdK9xVt3i420XTXtA3I56GqNm-ZGzKs/view?usp=sharing)

**Comment by samuro95** [comment]
Thanks a lot
