### ISSUE TITLE
upsampler

### ISSUE THREAD

**Issue by htyj123** [yingchen001/BAT-Fill#3]
Hi,
Thank you for your work,
I would be interested in your upsampler,could you please more detailed training parameters about the three dataset (train_up.sh) , I want to train my own upsampler.
Thanks a lot,

**Comment by yingchen001** [comment]
Thanks for your interest, you may find the parameters in options/train_options.py and base_options.py, those unlisted parameters are using their default values.

**Comment by htyj123** [comment]
Thank you
