### ISSUE TITLE
too slow to generate an image

### ISSUE THREAD

**Issue by hjq133** [yingchen001/BAT-Fill#4]
Thanks for your nice work and code! But I found it is too slow. When inference, how long does it take to generate an image? On my V100, it takes 40+ seconds to generate an image, is this reasonable? I found that most of the time is consumed in the transformer forward.

**Comment by yingchen001** [comment]
Hi hjq133,

Yes, it will take 30-60s per image for inference, as the autoregressive model predicts each token one by one (up to 32x32). Thanks.

Regards,
Yingchen

**Comment by hjq133** [comment]
Thanks for your reply, I just see it. 

Nice work! 

I will close this issue.
