### ISSUE TITLE
Some questions about the test？

### ISSUE THREAD

**Issue by ScarletBlaze** [yingchen001/BAT-Fill#6]
Thank you for your wonderful work. I would like to use your model as a baseline for comparison. Can you please tell me how you implemented the performance comparison based on the  irregular mask dataset （from Partial Convolutions (ECCV2018)） to accomplish different breakage ratios? Did you change the name of the mask file in the mask dataset first and then pass the bat_sample.py file?

**Comment by yingchen001** [comment]
Hi,

Yes, we randomly sample those masks based on their sizes and rename them to be the same as the ground truth. Thanks.
