### ISSUE TITLE
Question about the division of the CelebA-HQ dataset

### ISSUE THREAD

**Issue by tanbuzheng** [yingchen001/BAT-Fill#7]
Hi，could you tell me the details about how to divide the train and test sets of the CelebA-HQ dataset?

**Comment by yingchen001** [comment]
Hi, we follow the split of deepfill v1/2, you may find the flist [here](https://drive.google.com/drive/folders/1lpluFXyWDxTY6wcjixQGWX8jxUUMlyBW). Thank you for your interest in our work.

**Comment by tanbuzheng** [comment]
Thank you so much, I really appreciate to the writing idea of this paper and I hope to use it as a comparison to mine. 
Another request is that could you please share me the link of the png file of the celeba-hq, so that I can match it wih the flists. Since I concerned that the celeba-hq dataset I have obtained is not match with the flists.

**Comment by yingchen001** [comment]
I think it's okay to use either png or jpg version of CelebAHQ as long as you make it consistent for fair comparison.

**Comment by tanbuzheng** [comment]
OK, thank you!
