### ISSUE TITLE
Question about the batchsize

### ISSUE THREAD

**Issue by tanbuzheng** [yingchen001/BAT-Fill#8]
Hi, I would like to know the appropriate batchsizes for bat and upsampler when there is only one gpu?
In your coding setting, are there  4 gpus in parallel?

thanks!

**Comment by yingchen001** [comment]
Hi,

Sorry for the late reply, yes we're using 4 gpus in parallel, you can divide the batch size by 4 if you using one.

Regards,
Yingchen
